#!/usr/bin/env bash

# Delete first 25 characters (vs-code://open?url=file://)
request=${1:26}

# Decode URL
request=$(echo $request | echo -e "$(sed 's/+/ /g; s/%/\\x/g')")

# Replace &line= with :
request=${request/&line=/:}

# Launch Visual Studio Code
/usr/bin/code -g -r $request
